version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: url_shortener_db
    environment:
      POSTGRES_USER: ubot202
      POSTGRES_PASSWORD: ubot202
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d  # Auto-run migrations

  app:
    build: .
    container_name: url_shortener_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/url_shortener
      SPRING_DATASOURCE_USERNAME: ubot202
      SPRING_DATASOURCE_PASSWORD: ubot202
    depends_on:
      - postgres

volumes:
  postgres_data: